server.servlet.context-path=/casadoagricultor
server.port=8080
# Hibernate Configuration
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
hibernate.dialect=org.hibernate.dialect.MySQLInnoDBDialect
hibernate.hbm2ddl.auto=validate
hibernate.ejb.naming_strategy=org.hibernate.cfg.ImprovedNamingStrategy
hibernate.show_sql=true
hibernate.format_sql=true

spring.datasource.username=@spring.datasource.username@
spring.datasource.password=@spring.datasource.password@

spring.datasource.url=@spring.datasource.url@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

log4j.logger.org.apache.pdfbox.io.ScratchFileBuffer=WARN

## Main Quartz configuration
#org.quartz.scheduler.skipUpdateCheck = true
#org.quartz.scheduler.instanceName = DatabaseClusteredScheduler
#org.quartz.scheduler.instanceId = AUTO
#org.quartz.scheduler.jobFactory.class = org.quartz.simpl.SimpleJobFactory
#org.quartz.jobStore.class = org.quartz.impl.jdbcjobstore.JobStoreTX
#org.quartz.jobStore.driverDelegateClass = org.quartz.impl.jdbcjobstore.StdJDBCDelegate
#org.quartz.jobStore.dataSource = quartzDataSource
#org.quartz.jobStore.tablePrefix = QRTZ_
#org.quartz.jobStore.isClustered = true
#org.quartz.threadPool.class = org.quartz.simpl.SimpleThreadPool
#org.quartz.threadPool.threadCount = 5
#
#
### QUARTZ DATABASE
#org.quartz.dataSource.quartzDataSource.driver = com.mysql.cj.jdbc.Driver
#org.quartz.dataSource.quartzDataSource.URL = @quartzDataSource.URL@
#org.quartz.dataSource.quartzDataSource.user = @spring.datasource.username@
#org.quartz.dataSource.quartzDataSource.password = @spring.datasource.password@
#org.quartz.dataSource.quartzDataSource.maxConnections = 5


