-- MySQL Script generated by MySQL Workbench
-- Sat 04 Dec 2021 10:54:19 AM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema casa_do_agricultor
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema casa_do_agricultor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `casa_do_agricultor` ;
USE `casa_do_agricultor` ;

-- -----------------------------------------------------
-- Table `casa_do_agricultor`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `casa_do_agricultor`.`user` ;

CREATE TABLE IF NOT EXISTS `casa_do_agricultor`.`user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `last_user` BIGINT(20) NULL DEFAULT 1,
  `last_operation` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `name` VARCHAR(512) NOT NULL,
  `last_name` VARCHAR(512) NOT NULL,
  `email` VARCHAR(512) NOT NULL,
  `password` VARCHAR(512) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casa_do_agricultor`.`product_and_variety`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `casa_do_agricultor`.`product_and_variety` ;

CREATE TABLE IF NOT EXISTS `casa_do_agricultor`.`product_and_variety` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `last_user` BIGINT(20) NOT NULL DEFAULT 2,
  `last_operation` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `name` VARCHAR(512) NOT NULL,
  `name_2` varchar(512) DEFAULT NULL,
  `name_3` varchar(512) DEFAULT NULL,	
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_product_and_variety_user`
    FOREIGN KEY (`last_user`)
    REFERENCES `casa_do_agricultor`.`user` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casa_do_agricultor`.`price`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `casa_do_agricultor`.`price` ;

CREATE TABLE IF NOT EXISTS `casa_do_agricultor`.`price` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `last_user` BIGINT(20) NOT NULL DEFAULT 2,
  `last_operation` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `minimum` DECIMAL(10,2) NULL,
  `common` DECIMAL(10,2) NULL,
  `maximum` DECIMAL(10,2) NULL,
  `kg_common` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_price_user`
    FOREIGN KEY (`last_user`)
    REFERENCES `casa_do_agricultor`.`user` (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `casa_do_agricultor`.`ceasa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `casa_do_agricultor`.`ceasa` ;

CREATE TABLE IF NOT EXISTS `casa_do_agricultor`.`ceasa` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `last_user` BIGINT(20) NOT NULL DEFAULT 1,
  `last_operation` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `name` VARCHAR(256) NOT NULL,
  `city` VARCHAR(256) NOT NULL,
  `state` VARCHAR(256) NOT NULL,
  `country` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ceasa_user`
    FOREIGN KEY (`last_user`)
    REFERENCES `casa_do_agricultor`.`user` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casa_do_agricultor`.`cotation_file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `casa_do_agricultor`.`cotation_file` ;

CREATE TABLE IF NOT EXISTS `casa_do_agricultor`.`cotation_file` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `last_user` BIGINT(20) NOT NULL DEFAULT 2,
  `last_operation` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `successfully_processed` TINYINT NOT NULL DEFAULT 1,
  `filename` VARCHAR(256) NOT NULL,
  `format` VARCHAR(256) NOT NULL,
  `url` VARCHAR(512) NOT NULL,
  `storage_reference` VARCHAR(512) ,
  `saved_locally_or_cloud` VARCHAR(10),
  `ceasa_FK` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cotation_file_user`
    FOREIGN KEY (`last_user`)
    REFERENCES `casa_do_agricultor`.`user` (`id`),
  CONSTRAINT `fk_cotation_file_ceasa`
    FOREIGN KEY (`ceasa_FK`)
    REFERENCES `casa_do_agricultor`.`ceasa` (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `casa_do_agricultor`.`processing_errors_warnings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `casa_do_agricultor`.`processing_errors_warnings` ;

CREATE TABLE IF NOT EXISTS `casa_do_agricultor`.`processing_errors_warnings` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `last_user` BIGINT(20) NOT NULL DEFAULT 2,
  `last_operation` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `error_or_warning` VARCHAR(10) NOT NULL,
  `code` VARCHAR(256) NOT NULL,
  `problem` VARCHAR(256) NOT NULL,
  `solution` VARCHAR(512) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `casa_do_agricultor`.`cotation_file_processing_errors_warnings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `casa_do_agricultor`.`cotation_file_processing_errors_warnings` ;

CREATE TABLE IF NOT EXISTS `casa_do_agricultor`.`cotation_file_processing_errors_warnings` (
  `cotation_file_fk` BIGINT(20) NOT NULL,
  `processing_errors_warnings_fk` BIGINT(20) NOT NULL,
  PRIMARY KEY (`cotation_file_fk`,`processing_errors_warnings_fk`),
  CONSTRAINT `fk_cotation_file_processing_errors_warnings_file`
    FOREIGN KEY (`cotation_file_fk`)
    REFERENCES `casa_do_agricultor`.`cotation_file` (`id`),
  CONSTRAINT `fk_cotation_file_processing_errors_warnings_error`
    FOREIGN KEY (`processing_errors_warnings_fk`)
    REFERENCES `casa_do_agricultor`.`processing_errors_warnings` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casa_do_agricultor`.`cotation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `casa_do_agricultor`.`cotation` ;

CREATE TABLE IF NOT EXISTS `casa_do_agricultor`.`cotation` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `last_user` BIGINT(20) NOT NULL DEFAULT 2,
  `last_operation` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `from_day` DATE NOT NULL,
  `classification` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `origin` VARCHAR(255) NULL,
  `packaging` VARCHAR(255) NULL,
  `commun_weight` FLOAT NULL,
  `product_and_variety_FK` BIGINT(20) NOT NULL,
  `price_FK` BIGINT(20) NOT NULL,
  `cotation_file_FK` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cotation_product_and_variety`
    FOREIGN KEY (`product_and_variety_FK`)
    REFERENCES `casa_do_agricultor`.`product_and_variety` (`id`),
  CONSTRAINT `fk_cotation_price`
    FOREIGN KEY (`price_FK`)
    REFERENCES `casa_do_agricultor`.`price` (`id`),
  CONSTRAINT `fk_cotation_cotation_file`
    FOREIGN KEY (`cotation_file_FK`)
    REFERENCES `casa_do_agricultor`.`cotation_file` (`id`))
ENGINE = InnoDB;

ALTER TABLE `casa_do_agricultor`.`product_and_variety`  ADD INDEX `idx_product_and_variety_name` (`name`); 
ALTER TABLE `casa_do_agricultor`.`cotation`  ADD INDEX `idx_cotation_from_day` (`from_day`);  	


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
