<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>online.guessersoftware</groupId>
		<artifactId>casadoagricultor-api</artifactId>
		<version>${revision}</version>
	</parent>
	<artifactId>casadoagricultor-api-web-service</artifactId>
	<name>casadoagricultor-api-web-service</name>

	<properties>
		<java.version>1.8</java.version>
	</properties>

	<profiles>

		<profile>
			<id>dev</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<properties>
				<profileName>dev</profileName>
				<spring.datasource.username>test</spring.datasource.username>
				<spring.datasource.password>test</spring.datasource.password>
				<spring.datasource.url>jdbc:mysql://localhost/casa_do_agricultor</spring.datasource.url>
				<quartzDataSource.URL>jdbc:mysql://localhost:3306/casa_do_agricultor_quartz</quartzDataSource.URL>
			</properties>
		</profile>

		<profile>
			<id>live</id>
			<properties>
				<profileName>live</profileName>
				<spring.datasource.username>root</spring.datasource.username>
				<spring.datasource.password>7EL9MC69xte3qw2P</spring.datasource.password>
				<spring.datasource.url>jdbc:mysql://10.104.96.3/casa_do_agricultor</spring.datasource.url>
				<quartzDataSource.URL>jdbc:mysql://10.104.96.3:3306/casa_do_agricultor_quartz</quartzDataSource.URL>
			</properties>
		</profile>

	</profiles>

	<dependencies>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<!-- Add Log4j2 Dependency -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-log4j2</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
			<optional>true</optional>
		</dependency>

		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<scope>runtime</scope>
		</dependency>

		<!-- https://mvnrepository.com/artifact/org.apache.commons/commons-lang3 -->
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
		</dependency>

		<dependency>
			<groupId>org.apache.pdfbox</groupId>
			<artifactId>pdfbox</artifactId>
		</dependency>

		<!-- https://mvnrepository.com/artifact/org.jsoup/jsoup -->
		<dependency>
			<groupId>org.jsoup</groupId>
			<artifactId>jsoup</artifactId>
		</dependency>

		<!-- These validation dependencies are not working properly. The json error 
			message is not the one expected. Needs fix! -->
		<dependency>
			<groupId>javax.validation</groupId>
			<artifactId>validation-api</artifactId>
		</dependency>

		<!-- These validation dependencies are not working properly. The json error 
			message is not the one expected. Needs fix! -->
		<dependency>
			<groupId>org.hibernate.validator</groupId>
			<artifactId>hibernate-validator</artifactId>
		</dependency>

		<!-- These validation dependencies are not working properly. The json error 
			message is not the one expected. Needs fix! -->
		<dependency>
			<groupId>org.glassfish</groupId>
			<artifactId>javax.el</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-mail</artifactId>
		</dependency>

		<dependency>
			<groupId>javax.mail</groupId>
			<artifactId>javax.mail-api</artifactId>
		</dependency>

		<dependency>
			<groupId>online.guessersoftware</groupId>
			<artifactId>casadoagricultor-api-common</artifactId>
		</dependency>

		<dependency>
			<groupId>online.guessersoftware</groupId>
			<artifactId>casadoagricultor-api-micro-service-email-sender</artifactId>
		</dependency>

		<dependency>
			<groupId>com.google.cloud</groupId>
			<artifactId>google-cloud-storage</artifactId>
		</dependency>

		<!--<dependency>
			<groupId>org.quartz-scheduler</groupId>
			<artifactId>quartz</artifactId>
		</dependency>-->

	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>